// packages/solid/src/components/bosons/BasedProvider/BasedProvider.tsx
import { createContext, JSX } from 'solid-js'
import type { Component, Context as SolidContext } from 'solid-js'
import { BasedClient } from '@based/client'

/**
 * The props from the `BasedProvider` component
 */
type BasedProviderProps = {
  /** All the connection information that identifies you in the `Based` cloud. **/
  client: BasedClient
  /** Any component that you want to inject the `BasedClient` context. **/
  children: JSX.Element | JSX.Element[]
}

export const BasedContext: SolidContext<BasedClient> =
  createContext<BasedClient>()

const BasedProvider: Component<BasedProviderProps> = (
  props: BasedProviderProps,
) => {
  return (
    <BasedContext.Provider value={props.client}>
      {props.children}
    </BasedContext.Provider>
  )
}

/**
 * Alias to `BasedProvider`.
 */
const Provider = BasedProvider

export { Provider }
export default BasedProvider

// packages/vue/src/components/bosons/BasedProvider/BasedProvider.vue
<script lang="ts" setup>
import { provide } from 'vue'
import { BasedClient } from '@based/client'
import { BasedContext } from './index'

/**
 * The props from the `BasedProvider` component
 */
const props = defineProps({
  /** All the connection information that identifies you in the `Based` cloud. */
  client: BasedClient,
})

defineSlots<{
  default(): any
}>()

provide(BasedContext.CLIENT, props.client)
</script>

<template>
  <div class="based-io">
    <slot />
  </div>
</template>
